### PR TITLE
Update TickPool.cs

### PR DESCRIPTION
**Pull request by Bluscream**
Didn't i do this already? :thinking:

### CODE REVIEW

**Comment by Splamy** [comment]
Yes, but you pushed to master instead of develop
https://github.com/Splamy/TS3AudioBot/commit/bf37639676f48f12ee30cbbec39151e654c95b5f

**Comment by Bluscream** [comment]
Oh, can you push that from master to develop? A plugin of mine needs it.

**Comment by Splamy** [comment]
I'll probably finish my wip work then merge the develop back to master. The webinterface basics should be stable enough for normal use.

**Comment by Bluscream** [comment]
When you push from dev to master will that also merge the commits from master to dev?

**Comment by Splamy** [comment]
yes, but why do you need it? You are pushing to master only anyway all the time

**Comment by Splamy** [comment]
*cough* master *cough* https://github.com/Bluscream/TS3AudioBot/commits/master

**Comment by Splamy** [comment]
After a merge both branches will change, and will be the same. It doesn't matter anymore which is calles master which dev in that situation

**Comment by Bluscream** [comment]
yep, thanks :)

**Pull request closed without merging**
