### PR TITLE
add VersionSign 3.1.6

### PR DESCRIPTION
**Pull request by VerHext**
add VersionSign 3.1.6 Linux and Windows

### CODE REVIEW

**Comment by Splamy** [comment]
Hey I'd prefer not to change the default client version as 3.0.19.4 is our reference implementation.
If you wan to change your bot version there is the `QueryConnection::ClientVersion` setting to override with an own version.
Apart from that I would accept the remaining changes.

**Comment by Flakebi** [comment]
If I didn't oversee something, the windows signature is wrong (it's the same as the linux signature that works, but it should be different).

**Comment by VerHext** [comment]
@Splamy I change it to default... 

Yes the Windows and Linux signature is the same. But I think TeamSpeak has change it. Then all other versions need a differently signature. And i can´t use it with a other platform (client modify)...

**Comment by Splamy** [comment]
@Flakebi I was really confused too, I tested it but both work ^^

**Comment by Splamy** [comment]
Actually the windows hash is wrong. The correct one would be:
`73fB82Jt1lmIRHKBFaE8h1JKPGFbnt6\/yrXOHwTS93Oo7Adx1usY5TzNg+8BKy9nmmA2FEBnRmz5cRfXDghnBA==`
the Teamspeak server does some horribly wrong caching and thus accepts (partially) wrong hashes once one was connected.

**Comment by Bluscream** [comment]
We need to dig deeper

**Pull request merged**
