### PR TITLE
Update FfmpegProducer.cs

### PR DESCRIPTION
**Pull request by preterive**
Because the most Music is in 44,1

### CODE REVIEW

**Comment by Splamy** [comment]
Hace you actually tried that? Songs are speed up and pitched higher with this. Opus voice of teamspeak is in 48khz

**Comment by preterive** [comment]
I test it now
where is a list with the official specifications?

**Comment by Flakebi** [comment]
The 48 kHz specify the output sample rate of ffmpeg, not the rate of the input, so it doesn’t actually matter if your music uses 48 kHz or 44.1 kHz or something else.
You can find the used frequency in TeamSpeak in the client plugin sdk, it is also mentioned in this forum thread: https://forum.teamspeak.com/threads/133160-What-sample-rate-does-TS-use-for-audio

**Comment by Splamy** [comment]
We have also a list of specs here: https://github.com/Splamy/TS3AudioBot/blob/master/TS3Client/Ts3Enums.cs#L141-L152
Note that our ts3client only supports opus

**Pull request closed without merging**
